application: hackynews
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /index.(.+)
  static_files: index.\1
  upload: index.(.+)
- url: /lib/(.+)
  static_files: lib/\1
  upload: lib/(.+)
- url: /images/(.+)
  static_files: images/\1
  upload: images/(.+)